# Generated by Django 3.2.7 on 2021-11-08 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nemesis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='mobile_details',
            fields=[
                ('mob_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('price', models.IntegerField()),
                ('image_link', models.URLField(max_length=500)),
                ('product_link', models.URLField(max_length=500)),
            ],
        ),
    ]
