# Generated by Django 3.2.7 on 2021-11-09 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nemesis', '0002_mobile_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='reviews',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('heading', models.CharField(max_length=500)),
                ('verification_status', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1500)),
                ('mobile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nemesis.mobile_details')),
            ],
        ),
    ]
