# Generated by Django 3.2.7 on 2021-11-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nemesis', '0003_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
