# Generated by Django 3.2.7 on 2021-11-11 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nemesis', '0004_reviews_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
