# Generated by Django 3.2.7 on 2021-11-12 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nemesis', '0006_alter_reviews_verification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='user_id_id',
            field=models.IntegerField(default=1),
        ),
    ]
