# Generated by Django 3.2.7 on 2021-11-12 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nemesis', '0007_reviews_user_id_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='user_id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
