# Generated by Django 3.2.7 on 2021-11-18 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nemesis', '0008_alter_reviews_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='phone',
            field=models.CharField(default='NA', max_length=12),
        ),
    ]
